"use strict";(self.__LOADABLE_LOADED_CHUNKS__=self.__LOADABLE_LOADED_CHUNKS__||[]).push([[933],{1193:(e,r,t)=>{t.r(r),t.d(r,{default:()=>y});var n=t(9526),a=t(4769),l=t(7747),o=t(9653),s=t(2757),i=t(1293),c=t(7649),u=t(8446),E=t(9458),d=t(8861),m=t(3422),h=t(9669),g=t(8562),w=t(848);const p=()=>{const[e,r]=(0,n.useState)(!1);return(0,u.useCategory)({parameters:{id:"breaknow",levels:1}},{enabled:e}),n.createElement(a.z,{onClick:()=>{r(!0)}},"Send Failing Query")},_=({isError:e})=>{if(e)throw new Error("ERROR");return null},f=()=>{const[e,r]=(0,n.useState)(!1);return n.createElement(l.xu,{bg:"white"},n.createElement(l.xu,{layerStyle:"page-spacer-x",py:"1rem"},n.createElement(o.K,{gap:4},n.createElement(m.Z,{gap:3},n.createElement(s.X,null,"ErrorBoundary"),n.createElement(_,{isError:e}),n.createElement(i.x,null,"This page is wrapped in an ErrorBoundary component. This button will throw an error. The error is cought by the ErrorBoundary and an onError function is run to display a toast. Before throwing the error, if the Render Fallback option is selected, the ErrorBoundary will render the predefined fallback UI."),n.createElement(a.z,{onClick:()=>r(!0)},"Throw Error")),n.createElement(m.Z,{gap:3},n.createElement(i.x,null,"Click the button bellow to simulate failing query!"),n.createElement(p,null)))))},y=()=>{const[e,r]=(0,n.useState)(!1),{showAlert:t}=(0,g.VY)(),a=(0,E.Z)(),l=e=>{t({status:"error",title:e.message,message:a.formatMessage({id:"global.error.something_went_wrong"}),hasReset:!0})},o=e=>{const{status:r,statusText:t}=e.detail;l(new Error(`QUERY_ERROR ${r} ${t}`))};return(0,n.useEffect)((()=>{if(!w.sk)return window.addEventListener(h.tp,(e=>o(e))),()=>{window.removeEventListener(h.tp,o)}}),[l]),n.createElement(d.Z,{renderFallback:e,onError:l},n.createElement(c.X,{isChecked:e,onChange:e=>{r(e.target.checked)}},"Render Fallback"),n.createElement(f,null))};f.getTemplateName=()=>"styleguide-error-handling"}}]);